apiVersion: apps/v1
kind: Deployment
metadata:
  name: simple-node-app-blue
spec:
  replicas: 3
  selector:
    matchLabels:
      app: simple-node-app
      version: blue
  template:
    metadata:
      labels:
        app: simple-node-app
        version: blue
    spec:
      containers:
      - name: simple-node-app
        image: ajay112/docker-hub23/simple-node-app:blue
        ports:
        - containerPort: 3000
